name: gui_environment
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.1
  - attrs=22.1.0
  - blosc=1.21.1
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.5
  - conda-package-handling=1.8.1
  - console_shortcut=0.1.1
  - cryptography=37.0.4
  - curl=7.83.1
  - cytoolz=0.12.0
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.5.1
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - glib=2.72.1
  - glib-tools=2.72.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.3
  - intel-openmp=2022.1.0
  - jpeg=9e
  - kealib=1.4.15
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=7.83.1
  - libdeflate=1.13
  - libffi=3.4.2
  - libgdal=3.5.1
  - libglib=2.72.1
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libogg=1.3.4
  - libpng=1.6.37
  - libpq=14.5
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libzip=1.9.2
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - menuinst=1.4.19
  - mkl=2022.1.0
  - numpy=1.23.2
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - pcre=8.45
  - pillow=9.0.1
  - pip=22.2.2
  - pixman=0.40.0
  - ply=3.11
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.5
  - powershell_shortcut=0.0.1
  - proj=9.0.1
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.2.1
  - pywin32=303
  - rasterio=1.3.2
  - requests=2.28.1
  - ruamel_yaml=0.15.80
  - setuptools=65.3.0
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - sqlite=3.39.2
  - tbb=2021.5.0
  - tiledb=2.11.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tqdm=4.64.0
  - tzdata=2022c
  - ucrt=10.0.20348.0
  - urllib3=1.26.11
  - vc=14.2
  - vs2015_runtime=14.29.30139
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xerces-c=3.2.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - build==0.8.0
    - cycler==0.11.0
    - fonttools==4.37.1
    - geojson==2.5.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.3
    - pep517==0.13.0
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyqtwebengine==5.15.6
    - pyqtwebengine-qt5==5.15.2
    - pyyaml==6.0
    - tomli==2.0.1
