name: ra2ce_gui
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - mapbox
  - pip
  - pillow
  - python==3.9
  - rasterio
  - urllib3
  - pip:
    - geojson
    - pyqt5
    - pyyaml
    - PyQtWebEngine