name: gui_environment
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - pip
  - python==3.9
  - rasterio
  - urllib3
  - pip:
    - geojson
    - pyqt5
    - pyyaml
    - PyQtWebEngine