[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "guitares"
version = "0.0.3"
authors = [
    {name = "Maarten van Ormondt", email = "maarten.vanormondt@deltares-usa.us"},
]
requires-python = ">=3.10"
dependencies = [
    "geopandas >=0.8",
    "numpy",
    "pandas",
    "pyproj",
    "rasterio",
    "shapely",
    "numpy",
    "geojson",
    "Pillow",
    "matplotlib",
    "pyyaml",
    "pyqt5",
    "pyqtwebengine",
]

[tool.setuptools.package-data]
"guitares.pyqt5.mapbox.server"    = ["*.js", "*.html"]
"guitares.pyqt5.mapbox.server.js" = ["*.js"]
"guitares.pyqt5.mapbox.server.js.img" = ["*.png"]
"guitares.pyqt5.mapbox.server.css" = ["*.css"]
