element:
- style: listbox
  variable: active_event
  position:
    x: 10
    y: 10
    width: 300
    height: 120
  tooltip: Select event
  method: ddb_cfrss_events
  option_string:
    variable: event_names
- style: pushbutton
  position:
    x: 320
    y: 110
    width: 100
    height: 20
  text: Add event
  tooltip: Add event
  method: ddb_cfrss_events
- style: pushbutton
  position:
    x: 320
    y: 85
    width: 100
    height: 20
  text: Edit event
  tooltip: Edit event
  method: ddb_cfrss_events
  dependency:
  - action: enable
    checkfor: all
    check:
    - variable: nr_events
      operator: gt
      value: 0
    - variable: type
      operator: ne
      value: probabilistic_set
- style: pushbutton
  position:
    x: 320
    y: 60
    width: 100
    height: 20
  text: Delete event
  tooltip: Delete event
  method: ddb_cfrss_events
  dependency:
  - action: enable
    checkfor: all
    check:
    - variable: nr_events
      operator: gt
      value: 0
    - variable: type
      operator: ne
      value: probabilistic_set
- style: pushbutton
  position:
    x: 320
    y: 35
    width: 100
    height: 20
  text: Copy event
  tooltip: Copy event
  method: ddb_cfrss_events
  dependency:
  - action: enable
    checkfor: all
    check:
    - variable: nr_events
      operator: gt
      value: 0
    - variable: type
      operator: ne
      value: probabilistic_set
- style: radiobutton
  position:
    x: 320
    y: 10
  text: Individual event
  variable: radio_event
  value: '1'
  enable: false
  dependency:
  - action: 'on'
    checkfor: all
    check:
    - variable: type
      operator: ne
      value: probabilistic_set
- style: radiobutton
  position:
    x: 420
    y: 10
  text: Probabilistic set
  variable: radio_event
  value: '1'
  enable: false
  dependency:
  - action: 'on'
    checkfor: all
    check:
    - variable: type
      operator: eq
      value: probabilistic_set
- style: edit
  text: Surge
  variable: surge_source
  position:
    x: 500
    y: 110
    width: 80
    height: 20
  enable: false
  dependency:
  - action: visible
    checkfor: all
    check:
    - variable: type
      operator: ne
      value: probabilistic_set
- style: edit
  text: Tide
  variable: tide_source
  position:
    x: 500
    y: 85
    width: 80
    height: 20
  enable: false
  dependency:
  - action: visible
    checkfor: all
    check:
    - variable: type
      operator: ne
      value: probabilistic_set
- style: edit
  text: Wind
  variable: wind_source
  position:
    x: 500
    y: 60
    width: 80
    height: 20
  enable: false
  dependency:
  - action: visible
    checkfor: all
    check:
    - variable: type
      operator: ne
      value: probabilistic_set
- style: edit
  text: Rainfall
  variable: rainfall_source
  position:
    x: 500
    y: 35
    width: 80
    height: 20
  enable: false
  dependency:
  - action: visible
    checkfor: all
    check:
    - variable: type
      operator: ne
      value: probabilistic_set
