element:
- style: panel
  position:
    x: 10
    y: 290
    width: 480
    height: 100
  title: Description
- style: panel
  position:
    x: 10
    y: 160
    width: 480
    height: 130
  title: Properties
- style: panel
  position:
    x: 10
    y: 30
    width: 480
    height: 120
  title: Area
- style: edit
  position:
    x: 100
    y: 350
    width: 200
    height: 20
  variable: name
  text: Measure Name
  tooltip: Edit the name of the measure (no spaces allowed!).
  dependency:
  - action: enable
    checkfor: all
    check:
    - variable: add_edit
      operator: eq
      value: add
- style: edit
  position:
    x: 100
    y: 325
    width: 200
    height: 20
  variable: long_name
  text: Description
  tooltip: Edit the long name of the measure
- style: edit
  position:
    x: 90
    y: 250
    width: 50
    height: 20
  variable: elevation
  text: elevation_text
  tooltip: Edit the elevation
- style: pushselectfile
  position:
    x: 150
    y: 250
    width: 130
    height: 20
  text: Import Area Coordinates
  variable: polygon_file
  showfilename: 'yes'
  extension: '*.csv'
  tooltip: Import coordinates
  method: ddb_cfrss_measures
  dependency:
  - action: visible
    checkfor: any
    check:
    - variable: selection_type
      operator: eq
      value: polygon
- style: text
  position:
    x: 25
    y: 223
    width: 50
    height: 20
  text: Relative to
- style: radiobutton
  position:
    x: 80
    y: 220
    width: 50
    height: 20
  variable: elevation_type
  value: floodmap
  text: Base Flood Elevation
  tooltip: Set elevelation with respect to base flood elevation map
- style: radiobutton
  position:
    x: 80
    y: 200
    width: 50
    height: 20
  variable: elevation_type
  value: datum
  text: Datum (NAVD88)
  tooltip: Set elevelation with respect to datum
- style: popupmenu
  variable: property_type
  text: Property Type
  position:
    x: 100
    y: 170
    width: 100
    height: 20
  tooltip: Select property type for this measure
  option_string:
  - Residential
  - Commercial
  - Government
  - Religious
  - Industrial
  - Agricultural
  - Educational
  - All
  option_value:
  - RES
  - COM
  - GOV
  - REL
  - IND
  - AGR
  - EDU
  - ALL
- style: listbox
  variable: aggregation_area
  position:
    x: 20
    y: 40
    width: 200
    height: 90
  tooltip: Select aggregation area
  option_string:
    variable: active_aggregation_area_type}
  option_value:
    variable: active_aggregation_area_type}
  dependency:
  - action: visible
    checkfor: any
    check:
    - variable: selection_type
      operator: eq
      value: aggregation_area
- style: popupmenu
  variable: active_aggregation_area_type
  position:
    x: 230
    y: 110
    width: 150
    height: 20
  tooltip: Select projection
  method: ddb_cfrss_edit_measure_raise_property
  option_string:
    variable: aggregation_area_types
  dependency:
  - action: visible
    checkfor: any
    check:
    - variable: selection_type
      operator: eq
      value: aggregation_area
- style: pushcancel
  position:
    x: 370
    y: 10
    width: 50
    height: 20
- style: pushok
  method: ddb_cfrss_check_names
  position:
    x: 430
    y: 10
    width: 50
    height: 20
