element:
- style: listbox
  variable: active_scenario
  multivariable: handles.toolbox.cfrss.site(handles.toolbox.cfrss.active_site).site.active_scenarios
  max: '1000'
  position:
    x: 10
    y: 10
    width: 300
    height: 120
  tooltip: Select scenario
  method: ddb_cfrss_scenarios
  option_string:
    variable: scenario_names
- style: pushbutton
  position:
    x: 320
    y: 110
    width: 100
    height: 20
  text: Add scenario
  tooltip: Add scenario
  method: ddb_cfrss_scenarios
- style: pushbutton
  position:
    x: 320
    y: 85
    width: 100
    height: 20
  text: Delete scenario
  tooltip: Delete scenario
  method: ddb_cfrss_scenarios
  dependency:
  - action: enable
    checkfor: all
    check:
    - variable: nr_scenarios
      operator: gt
      value: 0
- style: pushbutton
  position:
    x: 320
    y: 60
    width: 100
    height: 20
  text: Edit scenario
  tooltip: Edit scenario
  method: ddb_cfrss_scenarios
  dependency:
  - action: enable
    checkfor: all
    check:
    - variable: nr_scenarios
      operator: gt
      value: 0
- style: edit
  position:
    x: 500
    y: 110
    width: 350
    height: 20
  variable: event_long_name_in_active_scenario
  text: Event
  enable: true
- style: edit
  position:
    x: 500
    y: 85
    width: 350
    height: 20
  variable: projection_long_name_in_active_scenario
  text: Projection
  enable: true
- style: edit
  position:
    x: 500
    y: 60
    width: 350
    height: 20
  variable: strategy_long_name_in_active_scenario
  text: Strategy
  enable: true
- style: checkbox
  position:
    x: 500
    y: 35
    width: 200
    height: 20
  variable: sfincs_finished
  text: SFINCS finished
  enable: false
- style: checkbox
  position:
    x: 500
    y: 15
    width: 200
    height: 20
  variable: fiat_finished
  text: FIAT finished
  enable: false
- style: checkbox
  position:
    x: 8880
    y: 60
    width: 100
    height: 20
  variable: run_exe
  text: Executable integrator
  enable: true
- style: pushbutton
  position:
    x: 880
    y: 35
    width: 100
    height: 20
  text: Run just SFINCS
  tooltip: Run SFINCS model for the selected scenario
  method: ddb_cfrss_scenarios
  dependency:
  - action: enable
    checkfor: all
    check:
    - variable: nr_scenarios
      operator: gt
      value: 0
- style: pushbutton
  position:
    x: 880
    y: 10
    width: 100
    height: 20
  text: RUN SCENARIO
  tooltip: Run the selected scenario
  method: ddb_cfrss_scenarios
  dependency:
  - action: enable
    checkfor: all
    check:
    - variable: nr_scenarios
      operator: gt
      value: 0
