element:
- style: listbox
  variable: active_strategy
  position:
    x: 10
    y: 10
    width: 300
    height: 120
  tooltip: Select strategy
  method: ddb_cfrss_strategies
  option_string:
    variable: strategy_names
- style: pushbutton
  position:
    x: 320
    y: 110
    width: 100
    height: 20
  text: Add strategy
  tooltip: Add strategy
  method: ddb_cfrss_strategies
- style: pushbutton
  position:
    x: 320
    y: 85
    width: 100
    height: 20
  text: Delete strategy
  tooltip: Delete strategy
  method: ddb_cfrss_strategies
  dependency:
  - action: enable
    checkfor: all
    check:
    - variable: nr_strategies
      operator: gt
      value: 0
